seed: 0
dataset: waymo/1cams_M

# ------------- Trainer ------------ #
trainer:
  type: models.trainers.MultiTrainer
  optim:
    num_iters: 30000
    use_grad_scaler: false
    cache_buffer_freq: -1
  render:
    near_plane: 0.1
    far_plane: 10000000000.0
    antialiased: false
    packed: false
    absgrad: true
    sparse_grad: false
    batch_size: 1
  losses:
    rgb:
      w: 0.8
    ssim:
      w: 0.2
    mask:
      w: 0.05
      opacity_loss_type: bce
    depth:
      w: 0.01
      inverse_depth: False
      normalize: False
      loss_type: l1
    affine:
      w: 0.00001
  res_schedule:
    double_steps: 250
    downscale_times: 2
  gaussian_optim_general_cfg:
    xyz:           {lr: 1.6e-04, lr_final: 1.6e-06, scale_factor: scene_radius}
    sh_dc:         {lr: 0.0025}
    sh_rest:       {lr: 0.000125}
    opacity:       {lr: 0.05}
    scaling:       {lr: 0.005}
    rotation:      {lr: 0.001}
  gaussian_ctrl_general_cfg:
    warmup_steps: 500
    reset_alpha_interval: 3000
    refine_interval: 100
    sh_degree_interval: 1000
    n_split_samples: 2
    reset_alpha_value: 0.01
    densify_grad_thresh: 0.0005
    densify_size_thresh: 0.003
    cull_alpha_thresh: 0.005
    cull_scale_thresh: 0.5
    cull_screen_size: 0.15
    split_screen_size: 0.05
    stop_screen_size_at: 4000
    stop_split_at: 15000
    sh_degree: 3

# ------------- Model ------------ #
model:
  Background:
    type: models.gaussians.VanillaGaussians
    init:
      from_lidar:
        num_samples: 800_000
        return_color: True
      near_randoms: 100_000
      far_randoms: 100_000
    reg:
      sharp_shape_reg:
        w: 1.
        step_interval: 10
        max_gauss_ratio: 10.
  RigidNodes:
    type: models.nodes.RigidNodes
    init:
      instance_max_pts: 5000
      only_moving: true
      traj_length_thres: 1.0
    ctrl:
      cull_scale_thresh: 0.1
      stop_screen_size_at: 30000
      stop_split_at: 20000
      cull_out_of_bound: true
    reg:
      sharp_shape_reg:
        w: 1.
        step_interval: 10
        max_gauss_ratio: 10.
      temporal_smooth_reg:
        trans:
          w: 0.01
          smooth_range: 5
    optim:
      ins_rotation:    {lr: 0.00001, lr_final: 0.000005}
      ins_translation: {lr: 0.0005,  lr_final: 0.0001}
  PartRigidNodes:
    type: models.nodes.PartRigidNodes
    init:
      instance_max_pts: 5000
      only_moving: false
      traj_length_thres: 0.0
      opacity_init_value: 0.99
    ctrl:
      refine_pose: true
      use_voxel_deformer: false
      ball_gaussians: false
      constrain_xyz_offset: false
      freeze_x: false
      freeze_s: false
      freeze_q: false
      freeze_o: false
      freeze_shs_dc: false
      freeze_shs_rest: false
      opacity_init_value: 0.99
      knn_neighbors: 5
      cull_scale_thresh: 0.1
      stop_screen_size_at: 30000
      stop_split_at: 20000
      cull_out_of_bound: false
    reg:
      sharp_shape_reg:
        w: 1.
        step_interval: 10
        max_gauss_ratio: 10.
      residual_reg:
        w_rot:   0.01
        w_trans: 0.01
    optim:
      ins_rotation:        {lr: 0.00001, lr_final: 0.000005}
      ins_translation:     {lr: 0.0005,  lr_final: 0.0001}
      smpl_rotation:       {lr: 0.00001, lr_final: 0.000005}
      seg_quat_residuals:  {lr: 0.0005,  lr_final: 0.0001}
      seg_trans_residuals: {lr: 0.0005,  lr_final: 0.0001}
  Sky:
    type: models.modules.EnvLight
    params:
      resolution: 1024
    optim:
      all: {lr: 0.01}
  Affine:
    type: models.modules.AffineTransform
    params:
      embedding_dim: 4
      base_mlp_layer_width: 64
      pixel_affine: False
    optim:
      all: {lr: 1.0e-5, weight_decay: 1.0e-6}
  CamPose:
    type: models.modules.CameraOptModule
    optim:
      all: {lr: 1.0e-5, weight_decay: 1.0e-6}

# ------------- render ------------ #
render:
  fps: 10
  render_full: True
  render_test: True
  render_novel:
    traj_types:
      - front_center_interp
    fps: 24
  vis_lidar: False
  vis_sky: False
  vis_error: False

# ------------- logging ------------ #
logging:
  vis_freq: 2000
  print_freq: 500
  saveckpt_freq: 15000
  save_seperate_video: True
